# Generated by Django 6.0.3 on 2026-03-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Mobile',
            field=models.CharField(max_length=12),
        ),
    ]
